project:
  type: website

website:
  title: "Project - do4ds"
  navbar:
    left:
      - href: eda-basic.qmd
        text: EDA
      - href: model.qmd
        text: Modeling

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    
execute:
  freeze: false